<center><h1> Corréction Série de Travaux Pratiques N° 6 - Machine Learning </h1></center>
<center><h2> Regression Logistique</h2></center>

---



# **Partie I : Regression Logistique**

Vous trouverez ci-joint un exemple d'utilisation d'algorithme de regréssion logistique avec les quatres étapes principales.

In [2]:
# Step 1: Import packages, functions
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Get data
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

# Step 3: Create a model and train it
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0, max_iter=100)
model.fit(x, y)

# Step 4: Evaluate the model
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score_ = model.score(x, y)
conf_m = confusion_matrix(y, y_pred)
report = classification_report(y, y_pred)

In [3]:
print('x:', x)
print('y:', y)
print('intercept:', model.intercept_)
print('coef:', model.coef_)
print('p_pred:', p_pred)
print('y_pred:', y_pred)
print('score_:', score_)
print('conf_m:', conf_m)
print('report:', report)

x: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y: [0 1 0 0 1 1 1 1 1 1]
intercept: [-1.51632619]
coef: [[0.703457]]
p_pred: [[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]
y_pred: [0 0 0 1 1 1 1 1 1 1]
score_: 0.8
conf_m: [[2 1]
 [1 6]]
report:               precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



# **Partie II : Classification Binaire**

L'objectif de l'ensemble de données "**diabetes.csv**" est de prédire, sur la base de mesures diagnostiques, si un patient **souffre de diabète ou pas**.

Ce dataset contient les caractéristiques suivants

**Grossesses**: Nombre de fois enceintes.

**Glucose**: concentration plasmatique de glucose à 2 heures lors d'un test oral de tolérance au glucose.

**Pression artérielle** : tension artérielle diastolique (mm Hg).

**Épaisseur de la peau** : épaisseur du pli cutané du triceps (mm).

**Insuline** : insuline sérique de 2 heures (mu U/ml).

**IMC** : Indice de masse corporelle (poids en kg/(taille en m)^2).

**DiabetesPedigreeFunction** : fonction généalogique du diabète.

**Âge** : Âge (ans).

**Résultat** : variable de classe (0 ou 1).

### **Questions :**

Étape 1 : Importer et afficher et explorer l'ensemble de données "**diabetes.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [4]:
# # Se connecter
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

In [ ]:
cd drive/My Drive/Colab Notebooks

/content/drive/My Drive/Colab Notebooks


In [5]:
# Binary Classification : Diabetes


In [5]:
import pandas as pd
data = pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
X=data[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']]
Y=data['Outcome']
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)
# print('X_train : ')
# print(X_train.head())
# print(X_train.shape)
 
# print('')
# print('X_test : ')
# print(X_test.head())
# print(X_test.shape)
 
# print('')
# print('y_train : ')
# print(Y_train.head())
# print(Y_train.shape)
 
# print('')
# print('y_test : ')
# print(Y_test.head())
# print(Y_test.shape)

In [9]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [10]:
lg.fit(X_test,Y_test)

d:\download folder\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
from sklearn.metrics import confusion_matrix, classification_report
x_pred=lg.predict_proba(X_test)
y_pred=lg.predict(X_test)
score_=lg.score(X_test,Y_test)
conf_m=confusion_matrix(Y_test,y_pred)
report=classification_report(Y_test,y_pred)

In [14]:
print("Model Score:", score_)
print("Predicted Probabilities:\n", x_pred)
print("Confusion Matrix:\n", conf_m)
print("Classification Report:\n", report)

Model Score: 0.8376623376623377
Predicted Probabilities:
 [[0.25679228 0.74320772]
 [0.92638565 0.07361435]
 [0.92325458 0.07674542]
 [0.94268551 0.05731449]
 [0.90049798 0.09950202]
 [0.08530356 0.91469644]
 [0.94597202 0.05402798]
 [0.98090442 0.01909558]
 [0.98057519 0.01942481]
 [0.94018915 0.05981085]
 [0.93882999 0.06117001]
 [0.81831924 0.18168076]
 [0.96030257 0.03969743]
 [0.24154896 0.75845104]
 [0.98172932 0.01827068]
 [0.84985262 0.15014738]
 [0.37834473 0.62165527]
 [0.98434578 0.01565422]
 [0.62598026 0.37401974]
 [0.71758074 0.28241926]
 [0.74191578 0.25808422]
 [0.851479   0.148521  ]
 [0.69804397 0.30195603]
 [0.53718247 0.46281753]
 [0.81599883 0.18400117]
 [0.93486655 0.06513345]
 [0.55638068 0.44361932]
 [0.89610774 0.10389226]
 [0.03381118 0.96618882]
 [0.84082227 0.15917773]
 [0.36501668 0.63498332]
 [0.06917416 0.93082584]
 [0.64589655 0.35410345]
 [0.93633664 0.06366336]
 [0.80286672 0.19713328]
 [0.93369872 0.06630128]
 [0.88772011 0.11227989]
 [0.09848409 0.90

# **Partie II : Classification Multi-Classe**

Pour cette partie, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

### **Questions :**

Étape 1 : Importer, afficher et explorer l'ensemble de données "**iris.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [15]:
# Multi-Class Classification : IRIS Dataset
df=pd.read_csv('iris.csv')
df.head

<bound method NDFrame.head of      sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]>

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [18]:
X=df[['sepal.length','sepal.width','petal.length','petal.width']]
Y=df['variety']
X

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [20]:
from sklearn.preprocessing import LabelEncoder
Y = LabelEncoder().fit_transform(Y)
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [25]:
from sklearn.linear_model import LogisticRegression

# Définir le modèle de régression logistique
mod = LogisticRegression(max_iter=200)

In [27]:
# Entraîner le modèle
mod.fit(X_train, Y_train)

# Faire des prédictions
y_pred = mod.predict(X_test)
x_pred = mod.predict_proba(X_test)

In [29]:
from sklearn.metrics import confusion_matrix, classification_report

# Évaluer le modèle
score_ = mod.score(X_test, Y_test)
conf_m = confusion_matrix(Y_test, y_pred)
report = classification_report(Y_test, y_pred)

# Afficher les résultats
print("Model Score:", score_)
print("Predicted Probabilities:\n", x_pred)
print("Confusion Matrix:\n", conf_m)
print("Classification Report:\n", report)

Model Score: 1.0
Predicted Probabilities:
 [[1.23127862e-04 1.39165813e-01 8.60711059e-01]
 [9.57393889e-01 4.26057872e-02 3.23911261e-07]
 [9.56988808e-05 6.43181521e-02 9.35586149e-01]
 [5.92473753e-03 7.99607896e-01 1.94467366e-01]
 [9.44913185e-01 5.50864437e-02 3.71445353e-07]
 [3.54041355e-05 1.80436329e-01 8.19528267e-01]
 [9.62664102e-01 3.73357165e-02 1.81074218e-07]
 [9.81247336e-03 9.71721733e-01 1.84657932e-02]
 [3.25608509e-03 9.06216277e-01 9.05276378e-02]
 [2.08455936e-06 2.51874579e-02 9.74810458e-01]
 [9.79580722e-01 2.04192232e-02 5.43550517e-08]
 [5.22448515e-06 1.85900687e-02 9.81404707e-01]
 [8.34932568e-04 4.12122673e-01 5.87042394e-01]
 [9.70760093e-01 2.92397394e-02 1.67778292e-07]
 [9.54775970e-01 4.52236375e-02 3.92450481e-07]
 [1.27511452e-02 7.36536261e-01 2.50712594e-01]
 [6.80447027e-03 7.84441049e-01 2.08754480e-01]
 [1.21678403e-05 8.05459866e-02 9.19441846e-01]
 [1.51122617e-03 7.93954382e-01 2.04534392e-01]
 [7.63630652e-05 1.13851916e-01 8.86071721e-0

In [35]:
# Définir de nouvelles valeurs pour la prédiction
new_values = [[5.1, 3.5, 1.4, 0.2], [6.7, 3.0, 5.2, 2.3]]  # Valeurs d'exemple

# Faire des prédictions pour les nouvelles valeurs
new_predictions = mod.predict(new_values)
new_probabilities = mod.predict_proba(new_values)

# Décoder les prédictions des nouvelles valeurs
#new_predictions_decoded = label_encoder.inverse_transform(new_predictions)

# Afficher les prédictions pour les nouvelles valeurs
print("New Values:", new_values)
#print("Predictions for New Values:", new_predictions_decoded)
print("Prediction Probabilities for New Values:\n", new_probabilities)


New Values: [[5.1, 3.5, 1.4, 0.2], [6.7, 3.0, 5.2, 2.3]]
Prediction Probabilities for New Values:
 [[9.77397972e-01 2.26019347e-02 9.28798550e-08]
 [1.03056875e-04 9.74326572e-02 9.02464286e-01]]


d:\download folder\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
d:\download folder\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
